#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
unset SSH_ASKPASS


# Add my scripts
export PATH="/home/destin/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/X11R6/bin"
export PATH=$PATH:~/scripts/:~/.composer/vendor/bin

# Add android studio path
export ANDROID_HOME=$HOME/Android/Sdk
export PATH=$PATH:$ANDROID_HOME/tools
export PATH=$PATH:$ANDROID_HOME/platform-tools

# Add go (golang) path
export GOROOT=/usr/lib/go-1.9
export PATH=$PATH:$GOROOT/bin
export GOPATH=$HOME/go
export GOBIN=$GOPATH/bin

# Add java paths
export JAVA_HOME=/usr/lib/jvm/java-8-oracle
export PATH=$PATH:/usr/lib/jvm/java-8-oracle/bin

# Add npm global path
export PATH=$PATH:$HOME/.npm-global/bin

# Force Wine to run in 32-bit mode
export WINEARCH=win32

# Set the default editor to vim
export EDITOR='vim'

# Aliases down here so they overwrite the
# set defined by oh-my-zsh

# Make ls more friendly
alias ls='ls --color=always -lh --group-directories-first'
alias bkp='cd ~/projects'
alias bkd='cd ~/Downloads'

# transfer.sh
transfer() {
    curl --progress-bar --upload-file $1 https://transfer.sh/$(basename $1) | tee /dev/null;
}

alias transfer=transfer

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[[ -f /home/destin/.config/yarn/global/node_modules/tabtab/.completions/serverless.zsh ]] && . /home/destin/.config/yarn/global/node_modules/tabtab/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[[ -f /home/destin/.config/yarn/global/node_modules/tabtab/.completions/sls.zsh ]] && . /home/destin/.config/yarn/global/node_modules/tabtab/.completions/sls.zsh
